### ISSUE TITLE
CardsContainer should be responsive and look good on all screen sizes

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/skeeep#27]
Also test on mobile devices, both with the responsive design setting of Chrome/Firefox/Safari and by going with a physical phone to your local React development server (http://192.168.X.Y:3000)

Tested:
- [x] Desktop Chrome
- [x] Desktop Firefox 
- [ ] Desktop Safari
- [ ] Mobile Chrome
- [ ] Mobile Firefox
- [x] Mobile Safari

**Comment by e-caste** [comment]
We can do this in two ways:
- get the dimensions of the largest card (given its content) and apply them to all the other cards so they're all the same size
- adjust the size of the cards individually based on their content (I think this is the default Bootstrap behavior)

**Comment by hesam1993** [comment]
I used the percentage for the height of the cards, so in the large screens they all have the same size, and while on the smaller screens they have different heights.
