### ISSUE TITLE
Make proper footer

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/skeeep#28]
- [x] brief description of what skeeep is
- [x] add skeeep and WEEE Open logo ("made by WEEE Open")
- [x] link to this repository
- [x] link to general skeeell page on the team's website with explanation of the project and contact to let people ask us to add their software to skeeep

Everything translated to:
- [x] English (e-caste)
- [x] Italian (e-caste)
- [x] Persian (hesam1993)
- [x] Simplified Chinese (itIsJim)

**Comment by e-caste** [comment]
@itIsJim and @hesam1993 could you add the missing Persian and Chinese translations for the footer?

**Comment by itIsJim** [comment]
I will do that
